### PR TITLE
Travis testing and many small fixes

### PR DESCRIPTION
**Pull request by crleblanc**
Added extensive integration tests, updated the README, added Docker support (via build.sh), and updated the vendored FTP server to fix a small bug related to the response code from mkdir (250 vs 257).  Also added .travis.yml for CI.

Fixed quite a few small bugs that were observed during testing, mainly around manipulating S3 key that didn't have a parent directory key.

This FTP server seems to behave nicely with Filezilla on relatively large nested directories (~1000 files).

Resolves issue#1.

### CODE REVIEW

**Comment by crleblanc** [comment]
Cancelled the older PR and created this one.  It's documented in the README, but basically we have to make PRs from the GeoNet/bucketFTP repo because we rely on encrypted environment variables stored in Travis.  Submitting a PR from a fork will fail to use these vars and therefore the tests will fail.

**Comment by crleblanc** [comment]
A few more commits.  Simplified how the tests are run.  "go test" now runs the client and server in the same process.  There's also another dockerfile used for running these tests which is also used by Travis.  This still builds the scratch based container to test that it works.

There's a few more checks for things like deleting an empty slice of objects.  S3 complains about this so trying to avoid it.

I'm seeing intermittent errors in Travis that I can't reproduce on my machine.  I see what's causing it: Travis is running two concurrent builds which are both modifying the same S3 bucket and therefore deleting or creating files used by the other instance.  We'll have to see why it isn't building one at a time.  I pushed a change that uses a UUID based on the MAC address which is unique in Travis.  This solves the concurrency issue.

**Comment by crleblanc** [comment]
We noticed on Soren's Mac that the ca certs and tzinfo weren't being packaged into the Docker container.  This was fixed and pushed to this branch (a change to the Dockerfile).

Soren, I noticed your testing on OSX with a GUI FTP client (Cyberduck?).  It sounds like our target is the hardware that will interact with this service so we may not be concerned with Cyberduck.  I've been testing against the command line FTP client in Linux (ftp), lftp, and FileZilla.  We haven't tested with our field equipment yet but I think that is the next priority once the earthquake aftermath settles down.

**Comment by crleblanc** [comment]
I have reproduced the behaviour seen by Soren on my mac at home.  Looking at this page it sounds like there are a lot of limitations with networking in Docker for Mac: https://docs.docker.com/docker-for-mac/networking/.

I think we should probably focus on running in a docker container running on a Linux host instead of a Mac since this is the target environment in AWS.

Running the Go tests and server executable natively in OSX seems to work fine so I'm thinking it's an issue with Docker for Mac.

**Comment by sorennh** [comment]
OK, I'd suggest someone else reviews this PR then, not using a Mac.

**Comment by sorennh** [comment]
Tests are working, so happy to close this.

**Review by sorennh — APPROVED** [review]
See comments

**Pull request merged**
